# -*- coding: utf-8 -*-
"""prac 1 AI(CS23016).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZALAmW7EiospWsRa30ARQ8mkC1NtRTZR

Sanika Takarkhede(CS23016)
"""

def magic_square(n):
    magic = [[0 for _ in range(n)] for _ in range(n)]

    i = 0
    j = n // 2

    for num in range(1, n * n + 1):
        magic[i][j] = num

        new_i = (i - 1) % n
        new_j = (j + 1) % n

        if magic[new_i][new_j]:
            i = (i + 1) % n
        else:
            i = new_i
            j = new_j

    # Print Magic Square
    print("Magic Square of size", n)
    for row in magic:
        for val in row:
            print(val, end="\t")
        print()

# Example
n = 3
magic_square(n)